project:
  type: website
  output-dir: _site

website:
  title: "MI01 Dashboard"
  navbar:
    left:
      - text: "Home"
        href: index.html
      - text: "County Dashboard"
        href: CountyOutputDashboard.html

format:
  html:
    theme: journal
    toc: true
    toc-location: left
